spring:
  profiles:
    include:
    - db
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_management_system
    username: root
    password: "@AdamLevine7"
#    url: jdbc:mysql://cms-aws-db-instance.cbq5rsvgsyif.ap-south-1.rds.amazonaws.com:3306/inventory_management_system
#    username: admin
#    password: "password"
    